### ISSUE TITLE
For loops vs mapreduce

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#103]
In several places in the code we have sums like this:
```julia
nep=nep_gallery("qdep0");
n=size(nep,1); S=randn(3,3);; V=randn(n,3); 
z=zeros(ComplexF64,n);
for i=1:size(nep.A,1)
   Fi1=nep.fi[i](S)[:,1];
   VFi1=V*Fi1
   z[:] += nep.A[i]*VFi1
end
```
This can also be done with a single `mapreduce` call:
```
z2=mapreduce(jj -> nep.A[jj]*(V*nep.fi[jj](S)[:,1]), +, [1:size(nep.A,1);])
```
I'm not so experienced with mapreduce. Does someone know right away if this is advisable?

**Comment by maxbennedich** [comment]
My experience with mapreduce and other higher order functions is that they can be very slow to JIT compile and execute the first time (which has thrown me off a few times when profiling code), but once compiled they should perform just as well as explicit looping. They shorten the code, and prevent mistakes in the boilerplate code.

The two drawbacks I see is 1) it takes a while to get used to the syntax; some probably find it harder to read and maintain, and 2) it can be more difficult to edit, for example if you want to add a conditional statement, or terminate early, in that for loop. That said, I try to use them unless I find that the code becomes too unwieldy.

On a minor note, the last argument can be shortened to `1:size(nep.A,1)` or, if A is a vector, `1:length(nep.A)`.

**Comment by jarlebring** [comment]
So not better in terms of performance?

I do see your point that it can prevent mistakes. The code above gives the same performance as mapreduce only if I change to a `[:] +=` to `.+=`, otherwise the for-loop is slower.

(When we moved from MATLAB to julia we tried to stay away from the length command since the behaviour for matrices is different.)

**Comment by maxbennedich** [comment]
I think the performance should be the same (since `mapreduce` is implemented in Julia), but that assumes that you "do everything right" with the for loop, including type stability, fusing dots, and `@inbounds`. So in that sense, perhaps it's easier to write correct and efficient code using the higher order functions.

**Comment by jarlebring** [comment]
Thanks for clarifying this. Then I suggest we see the above example as the border case. If the function is more complicated we avoid it, if it is like this or easier mapreduce _can_ be used. I'll keep this issue open so we remember to go through it at a meeting.

**Comment by maxbennedich** [comment]
I spoke a bit too soon; fusing dots will not automatically be added in the above example, since the operator used is still `+` and not `.+=`. Allocating additional space during summation of the `z` vectors should be a negligible cost compared to the matrix-vector multiplication, but if the arrays being added are large, it could be costly. Consider this example:
```julia
julia> N = 1024 ^ 2;

julia> A = [ones(N), ones(N), ones(N), ones(N)];

julia> @btime reduce(+, A);
  7.968 ms (6 allocations: 24.00 MiB)

julia> @btime (S = copy(A[1]); for B in A[2:end]; S .+= B; end; S);
  4.797 ms (13 allocations: 8.00 MiB)
```
A for loop is almost twice as fast, and allocates 3x less memory. The difference is due to the temporary matrices being allocated during the summation. To avoid that, one could do something like this:
```julia
julia> a ⊕ b = a .+= b;

julia> @btime reduce(⊕, view(A,2:length(A)), init=copy(A[1]));
  3.576 ms (8 allocations: 8.00 MiB)
```
Again, I don't think this makes a practical difference for the example above, since this is not going to be what is taking the majority of time (if it's a concern, there are other optimizations we could make that would be more beneficial, cf. #101). But we should keep this in mind if for example reducing large matrices.

**Comment by maxbennedich** [comment]
Just a small note that one can use do-blocks with `map` and `mapreduce`, [as described here](https://docs.julialang.org/en/latest/manual/functions/#Do-Block-Syntax-for-Function-Arguments-1). I think this style is more readable when the function body is more than one line, since it puts the collection argument at the beginning of the expression instead of at the end.

**Comment by jarlebring** [comment]
Cleaning up issues. This issue is information only. Closing.
