### ISSUE TITLE
naive run gun+nleigs throws error  

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#137]
I think the following could  should "work" although a bit slow: 
```julia
julia> nep=nep_gallery("nlevp_native_gun");
julia> square=ComplexF64[-1-1im;-1+1im;1+1im;1-1im];
julia> nleigs(nep, 160^2 .+ 40*square,displaylevel=1)
``` 
At the moment it throws a `MethodError`.  It seems to be a problem with Matrix vs Vector.

**Comment by maxbennedich** [comment]
Good find! That code path seems to never have been tested. I wrote up a fix. The example above now runs, although it doesn't find any eigenvalues?

**Comment by maxbennedich** [comment]
Is there supposed to be an eigenvalue present in that region? The following works after my commit:
```julia
julia> λ,_ = nleigs(nep, 22345 .+ 40*square,displaylevel=1);
Linearization converged after 8 iterations
 --> freeze linearization
  iteration 28: 1 of 1 < 1.0e-10

julia> λ
1-element Array{Complex{Float64},1}:
 22345.116783765003 + 0.6449985984551109im
```

**Comment by jarlebring** [comment]
I'm not completely sure the region contains eigvals. Your example is better.

**Comment by jarlebring** [comment]
This also works (and is less constructed to be around the eigenvalue):
```
julia> λ,v=nleigs(nep, 150^2 .+ 40*square,displaylevel=1)
```

**Comment by maxbennedich** [comment]
Hmm, that doesn't find any eigenvalues for me, did you change the square? `200*square` for example works for me.

I just added a test for this in the same branch I did the fix, since this code path was not tested anywhere (feel free to alter the region or test to make it less constructed): https://github.com/nep-pack/NonlinearEigenproblems.jl/commit/08e0b9f5a910efd0f7fdb717196118b73a7d98d1

**Comment by jarlebring** [comment]
You're right. Good. I actually used 40^2 when I tested ... not sure how copy-paste can remove things ;-)
