### ISSUE TITLE
EigSolver refactorization for consistency

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#32]
Migrated from gitr @ kth # 29:

Currently a `LinSolver` is passed to the method by passing a function `linsolvercreator::Function=default_linsolvercreator`, whereas the specification of `EigSolver` is passed as a Type  `eigsolvertype::DataType=DefaultEigSolver`. This is indeed inconsistent as @eringh and @pup wrote:

@eringh in #26:
> I think we potentially should redo the EigSolver in the same way as the LinSolver. As it is now a LinSolver comes with a creator function that creates a LinSolver. However, the EigSolver is still in the previous thinking where a DataType is provided, and directly used for creating the solver through the constructor. Maybe the variety of EigSolvers is not that big as for LinSolvers (where for example a preconditioner is much easier to use with the "new" structure). However, is seems a bit confusing to have two different ways of working, especially since they come from the same module. Should we add this the the check list?

@pup wrote in #26:
> As @eringh mentioned in one of the previous comments, there are some differences between how we implement the LinSolver and EigSolver types. EigSolver and and its derivatives are not parametric types and the there is no creator function involved. Although this doesn't make much difference to the method user, who will just type in the name of the solver/creator function as an arguement, it is good to have consistency, as Emil mentioned. The only downside I can think of is that a lot of our code assumes the current implementation of EigSolver, and could break, but that of course is fixable. @eliasj , Should I go ahead with changing the EigSolver implementation?

I agree that they are inconsistent, and this seems unnatural. I'm not yet sure what the best solution is. 

Note that a `LinSolver` is conceptually slightly different from a `EigSolver` since a linear system has a right-hand side. A `LinSolver` object can be used for different right-hand sides, whereas an `EigSolver` does not a have a corresponding input (except for arguably the target and the number of eigenvalues, but still quite different).

I think Julia is designed for extensive use of types (and not function pointers), e.g., look at the modern way of doing orthogonalization in IterativeMethods, where one passes the type `IterativeSolvers.OrthogonalizationMethod`, where the corresponding function is called by
```
        H[k+1,k] = orthogonalize_and_normalize!(VV, vv, view(H,1:k,k), orthmethod)
```
This seems like a third approach. I think we need to think about if we can come up with a similar construction for our case, before we do any actual code refactorization.

**Comment by meleg** [comment]
I am not sure if I should post this here, but this issue seems related. Quoting @jarlebring 

> I think Julia is designed for extensive use of types (and not function pointers) 

it feels like we should aim for using more types rather then functions. For example we should also change `errmeasure` that at the moment is a function. We can define `errmeasure` as a type and we need to have a function `compute_error` (or any other name) that takes as input  `errmeasure,s,v` where `(s,v)` is an eigenpair approximation and `compute_error` may have different values such as `default` (residual) and the function  `compute_error` may be dispatched to compute differently the error for the different formats of the NEP (DEP,PEP,SPMF,...), and the user can define his own type `errmeasure` and overload the function `compute_error` to measure the error in the way that he wants.

If you agree I can implement the changes that I described.

**Comment by jarlebring** [comment]
I think it's good. You can post your comment as a new issue so we can track it better.

**Comment by jarlebring** [comment]
For now replaced by #39
