### ISSUE TITLE
Unit testing in github + continuous integration

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#36]
According to the julia docs
https://docs.julialang.org/en/release-0.6/manual/packages/#Generating-the-package-1
it should be possible to make the unit-tests run on a continuous integration system (Travis and/or AppVeyor) reasonably easy, i.e. on a separate server which carries out tests after each commit. I think we should start using this if we can get it for free. Fixing this issue requires more understanding of continuous integration systems and github than actual programming.

**Comment by eringh** [comment]
Looking at commits such as 04ec8596b61ed26eb931ffee2471382b7a4ba1d9 and 6fa246bce78394905db32b38abe898d5964e8ec7 it seems as if there is an upper limit of 50 minutes that the tests are allowed to run before aborting. We should consider this when constructing the test.

**Comment by jarlebring** [comment]
I agree. I see this as a conceptual difficulty, a bit computer science vs numerics. In CS thinking you run the code and assume it works if all lines in the code are executed with expected result (coverage), even if the problem/matrices are small. In most of our tests we run it on benchmark problems which are challenging for the algorithm: mostly large-scale problems. Some algorithms only work for large-scale problems.

**Comment by maxbennedich** [comment]
Travis CI and test coverage set up and integrated with Github, so that each commit is built and tested. Configuration is done in [.travis.yml](https://github.com/nep-pack/NonlinearEigenproblems.jl/blob/master/.travis.yml).

[Travis CI build](https://travis-ci.org/nep-pack/NonlinearEigenproblems.jl)
[Coveralls test coverage](https://coveralls.io/github/nep-pack/NonlinearEigenproblems.jl?branch=master)
[Codecov test coverage](https://codecov.io/gh/nep-pack/NonlinearEigenproblems.jl)
