### ISSUE TITLE
Inner solves and projected problems

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#38]
Several of the methods are inner-outer iteration methods. At some point in the algorithm you need to solve a smaller problem (typically the Galerkin projection of the problem). In commit  6554628cb1a5d91d5c1c622cd44d271f7908e3e4 and the following commits, I have made an attempt to make this systematic. The inner solves are controlled by the helper functions in `inner_solver.jl`. I have also already included it in `iar`, as an alternative way to extract eigenpairs complement to the computation of eigenvalues from the hessenberg matrix. 

Consistent with IAR we now need to incorporate this system into

* [x] Jacobi-Davidson 
* [x] NLArnoldi 
* [x] TIAR

and we should and inner solver helper functions corresponding to a couple of other methods, at least

* [x] sgiter
* [x] iar (yes, thereby you can do inner and outer iterations with IAR) 
* [x] augnewton
* [x] polyeig
* [x] beyncontour

(I don't think we need to include all methods we have as inner solves.)

**Comment by eringh** [comment]
Jacobi-Davidson already had a `proj_eig_solver` argument to solve the inner problem since 
5343fa28e20dd8af2f7e69856221f99b587742db. However, that was in need of refactorization because of the EigSolver refactorization #32.

Regardless I think we should aim for consistency here.

**Comment by jarlebring** [comment]
Indeed, I know both you and @upadpup are solving projected problems in JD and nlar already. The proposed solution is inspired how we needed in there. This solution should hopefully make both JD and nlar cleaner and indeed consistent.

**Comment by jarlebring** [comment]
Todo fixed.

**Comment by eringh** [comment]
Another thought on this. Should we pass the type of arithmetic as well?
Our outer methods are typed in the arithmetic used, and since we are using these methods as inner solvers as well we have the opportunity to type them. Should we pass on that type from the outer to the inner in the kwargs.
What do you think, @jarlebring ?

**Comment by eringh** [comment]
Yes I think so. Although I am not sure we need it to compile the `inner_solve`  as that is more of a wrapper, and as long as we pass it on to the actual inner solver method most of it should be fine.

However, it might be good practice to pass it as an argument anyway, since we (probably) want it for all methods. And I don't think it will ever cause a problem.

Ergo: I agree to pass it as a required parameter, but for a different reason.
