### ISSUE TITLE
From passing functions to passing types

### ISSUE THREAD

**Issue by meleg** [nep-pack/NonlinearEigenproblems.jl#39]
Many functions that we have implemented have as arguments other functions. Quoting @jarlebring in the issue #32 
> I think Julia is designed for extensive use of types (and not function pointers) 
Therefore we should try to avoid every function-passing and replace it with a type-passing. 

For example, quoting myself from the issue #32 

> We should also change `errmeasure` that at the moment is a function. We can define `errmeasure` as a type and we need to have a function `compute_error` (or any other name) that takes as input  `errmeasure,s,v` where `(s,v)` is an eigenpair approximation and `compute_error` may have different values such as `default` (residual) and the function  `compute_error` may be dispatched to compute differently the error for the different formats of the NEP (DEP,PEP,SPMF,...), and the user can define his own type `errmeasure` and overload the function `compute_error` to measure the error in the way that he wants.

I think that this should also be the spirit for passing a linsolver (currently done with `linsolvercreator`). We should not pass a function but a type. Clearly a pre-computation may be needed in this case. This can be done in the same fashion of the function `iar_chebyshev` for the argument `compute_y0_method` that requires a pre-computation.

Therefore I here attach a check list for these changes, namely the following arguments should be types
- [ ] `errmeasure`
- [ ] `linsolvercreator`
- [ ] `EigSolver`

At the moment we agree that `errmeasure` should be changed. What about the others? Refer to the discussion in the issue #32 for `EigSolver`.

**Comment by jarlebring** [comment]
Nice.  I think `errmeasure` is certainly the easiest one, but still not trivial. It would be nice to have if we can have several easily accessible ways to measure the error:

`DefaultErrmeasure`
`ResnormErrmeasure`
`BackwardErrmeasure` (for spmfs:  Resnorm / (||A_1|| |f_1(λ)|+... ||A_m|| |f_m(λ)|)
`ReferenceErrmeasure` measure distance to a precomputed reference solution.  

The interface to compute an errmeasure could be  e.g.
```
function eval_errmeasure(::Type{ResnormErrmeasure},nep,λ,v)
   return norm(compute_Mlincomb(nep,λ,v))/norm(v);
end
```
 
That would be enough for `ResnormErrmeasure`, but we may need more functions.  Note that `BackwardErrmeasure` would ideally compute ||A_1|| ... || A_m|| before the main iteration loop. I don't see how that could be done without also adding a `precompute_data` function (like we now have for `y0`-computation in `iar_chebyshev`). `ReferenceErrmeasure` would need the user to provide the reference solution information somehow. 

The other ones (linsolvecreator and eigsolver) are a bit different since they certainly need precomputation, and linsolvecreator needs to be called several times.

**Comment by jarlebring** [comment]
Considering that @meleg will be essentially offline for the next 6 months and the fact that this issue is not sufficiently concrete for someone else to work on: @meleg could you turn this into smaller clearer issues? Or transform it into something someone else could work on.

**Comment by meleg** [comment]
I would focus only on `errmeasure`, which should be passed as type. I think we should follow the suggestions you gave in on old answer. I only suggest to not use `BackwardErrmeasure` as name, but the name `RelativeErrmeasure`. I will open an new issue about this.
