### ISSUE TITLE
Problems with Compute_Mlincomb

### ISSUE THREAD

**Issue by eringh** [nep-pack/NonlinearEigenproblems.jl#55]
The pull request #53 seemed ok when we merged it. However, it has given some problems for us now. Typically we have observed that we get stuck in infinite loops, which gives Stack Overflow (I get it on my JD-branch now, or try the state given by the commit ea266febc3bd7479ef9933a3c3e6680685024b5e but without typing `a` as a `Vector`). Or, because of the strict typing we get ambiguous calls (see cba5b037a9bd3826cec5367c8f4885a08b086356).

Perhaps we should not implement the transition functions but require the type developer to do that in order to use the relevant methods.

**Comment by jarlebring** [comment]
There was indeed a problem when I merged it. I thought I resolved it 17065eda595931acc29c4e40f4220d89a9895e09. Are you sure this is still a problem? Can you give an example?

**Comment by eringh** [comment]
I cannot commit anything right now, because I have local changes in my directory. But if you checkout master at ea266febc3bd7479ef9933a3c3e6680685024b5e, and then change line 121 in `NleigsTypes.jl` to
```
compute_Mlincomb(nep::LowRankFactorizedNEP, λ::T, V::Union{Vector{T}, Matrix{T}}, a = ones(T, size(V, 2))) where T<:Number =
```

(that is remove the added typing of `a` as a vector). This created a horrible "silent death" on my computer and a segfault for @maxbennedich. When forcing a print into the mapping of Mlincomb(...)=Mlincomb!(...) it created a stack overflow for me.
I think it should have thrown an ambiguous error, but it didn't.

**Comment by jarlebring** [comment]
I prefer first look closer at why that happened (and what was wrong in our reasoning) than forcing type-developers to handle one more function. I'll look into it.

**Comment by jarlebring** [comment]
Why this happened part 1. Note that ea266febc3bd7479ef9933a3c3e6680685024b5e made the type of `a` more specific _and_ changed it from a kwarg to an arg.  This is the reason there was no "ambiguous error" before ea266febc3bd7479ef9933a3c3e6680685024b5e. Julia correctly saw that it was more specific than the `compute_Mlincomb(::NEP,.λ::Number,V::Union{AbstractMatrix,AbstractVector})`. 

```
abstract type NEP end
struct DEP <: NEP end
struct PEP <: NEP end

foo(nep::NEP,λ::Number,V::Union{AbstractMatrix,AbstractVector})=foo!(nep,λ,copy(V))
foo(nep::NEP,λ::Number,V::Union{AbstractMatrix,AbstractVector}, a::Vector)=foo!(nep,λ,copy(V), a)
foo!(nep::NEP,λ::Number,V::Union{AbstractMatrix,AbstractVector})=foo(nep,λ,V)

function foo(nep::DEP,λ::X,V::Union{Matrix{X},Vector{X}};a=0) where X<:Number
    println("foo(DEP) a:",a)
end
dep=DEP()
V=[5]
λ=2
foo(dep,λ,V)  # Works. prints 0
foo(dep,λ,V,a=3) # Works. prints 3
```

**Comment by jarlebring** [comment]
Why this happend part 2. If we continue and now call it in a bit unusual way  
```
V=[5.0]
λ=2
foo(dep,λ,V) # Stack overflow
```
The last call callls the foo-definition in # 1 since we dont have `typeof(λ) = eltype(V)`. The call # 1 calls foo-definition in # 3, which calls foo definition # 1 etc.

Note the function definition in # 4 is only valid when the types are consistent.

**Comment by jarlebring** [comment]
Why this happened part 3. The inconsistent type situation could occur more often than the example above due to that one of the wrappers did not preserve type (prev commit).

**Comment by jarlebring** [comment]
This is becoming a bit of a monologue. Although this issue was generated by a bug and unusual `compute_Mlincomb`-definition forcing same types, I think there is a bigger conclusion to make. Having  `compute_Mlincomb` and `compute_Mlincomb!` point to each other is error prone with computers crashing even. Bugs similar to above seem likely.

Solutions:

1. Make a check which errors if there is cyclic calls in compute_Mlincomb, e.g., by  checking the `stacktrace()`. This would require computation and not so nice in a core wrapper. 
2. Remove all the default pointing.  Forces all type-developers to handle both compute_Mlincomb and compute_Mlincomb!. 
3. Remove the pointer `compute_Mlincomb` -> `compute_Mlincomb!` but keep  `compute_Mlincomb!` -> `compute_Mlincomb`. For type-developers implementing `compute_Mlincomb` nothing changes. Type-developers implementing `compute_Mlincomb!` would need to explicitly provide the pointers for `compute_Mlincomb`. For algorithm developers nothing changes.
 
At the moment I would be in favor of 1 if it can be done in a non-hacky way. Otherwise 3.

**Comment by maxbennedich** [comment]
We discussed option 1 a bit yesterday, but couldn't figure out a way to do
it nicely. Option 3 seems ok to me too.

**Comment by jarlebring** [comment]
I tried another middle way in the two previous commits: Keep the pointer `compute_Mlincomb(nep,λ,V, a) -> compute_Mlincomb!(nep,λ,copy(V), a)` but replace `compute_Mlincomb(nep::NEP,λ,V)` with a warning+error how to activate the pointer `compute_Mlincomb(nep,λ,V)`-> `compute_Mlincomb!(nep,λ,V)`. 

I think this cannot cause infinite recursion because we have a function which `compute_Mlincomb!(nep::NEP,λ,V, a)` which points to (by some computation) `compute_Mlincomb!(nep::NEP,λ,V)`.

It's basically option 3, but only for  `compute_Mlincomb(nep,λ,V)` not for  `compute_Mlincomb(nep,λ,V,a)`.

**Comment by jarlebring** [comment]
This midway solution seems to work well so far, so I will close this issue for now.

**Comment by eringh** [comment]
With this issue closed, I will delete the branch https://github.com/nep-pack/NonlinearEigenproblems.jl/tree/breaking_Mlincomb
