### ISSUE TITLE
Set projection matrices slow on 0.7

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#58]
The construction of projected NEPs is very slow on julia 0.7:
```
julia> nep = nep_gallery("nlevp_native_gun");
julia> pnep=create_proj_NEP(nep);
julia> Q=randn(size(nep,1),20);
julia> @time set_projectmatrices!(pnep,Q,Q);
 38.810410 seconds (81.21 k allocations: 22.594 MiB, 0.01% gc time)
```
This causes `nlar` to be extremely slow on 0.7.  It has to to with the lines 
```
        for i=1:m
            B[i]=W'*nep.orgnep_Av[i]*V;
        end
```

Anyway on the todo-list for projected solve is to have the possibility to extend the projection without recomputing all the individual matrices (`extend_project_matrices!(pnep,x,y)`), which would probably solve this problem.

**Comment by maxbennedich** [comment]
Good find! This is caused by `W'` having changed type from materialized (such as `Matrix`) in Julia 0.6 to `Adjoint` in Julia 0.7, which leads to full multiplication instead of sparse. A simple fix is to materialize the `Adjoint` by wrapping it in `copy` ([fixed here](https://github.com/nep-pack/NonlinearEigenproblems.jl/commit/a9bcf8376a242fea5481512cd42d646808714f4c)). I've seen several issues about this on Discourse, and we might have more of these instances in our code, perhaps this is what makes `wep_small` so slow.

**Comment by jarlebring** [comment]
Great. Thanks! Closing in favor of #59.
