### ISSUE TITLE
Not all tests are executed

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#92]
I think the spmf-test spmf.jl is currently never executed. Maybe there are more. If someone looks into this, maybe he can also exclude files containing # and ~, which are temporary files generated by emacs and cause me some trouble.

**Comment by jarlebring** [comment]
Maybe it has something to do with my commit 08ecec4743a6e6334185b0a4c6d8210f86fbbf6b and how I used `@onlybench`.

**Comment by maxbennedich** [comment]
Alright, I'll take a look.

**Comment by maxbennedich** [comment]
The reason that the test was not run was that there was an `end` statement missing in the newly added test, which caused parsing of the file to fail. I fixed it by adding the `end` statement (and indented the code in the `for` block to make it more clear, but feel free to rearrange it).

While this solves this particular test, it could be useful if the test runner would actually throw an error and fail the build for invalid tests, instead of silently ignoring them. I'll see if I can update it, and also exclude temporarily generated files.

**Comment by jarlebring** [comment]
Ah. Sorry about that.
